@localhost=http://localhost:3000/
@sau=http://sau.scu.edu.cn/
@json=Content-Type: application/json

### 反馈
POST {{localhost}}feedback
{{json}}

{
    "data": "WTFFFFFFFFFFFFFFFFFFF"
}

### 搜索
POST {{localhost}}search
Content-Type: application/json;charset=UTF-8

{
    "ci": "",
    "cn": "智能控制",
    "pi": ""
}

### 新闻列表
GET {{localhost}}newsList?page=3
{{json}}

### 活动列表
GET {{localhost}}prelist?page=1
{{json}}

### 新闻内容
GET {{localhost}}newsContent?newsid=6315

### 竟会是无效请求 只能得到第一页
POST {{sau}}/Club/LClub
Content-Type: application/x-www-form-urlencoded; charset=UTF-8

{
    "pi": "9"
}

### 申请状态 1 驳回 0 通过 空为全部
POST {{localhost}}searchStatue
{{json}}

{
    "clubname": "",
    "status": "1",
    "pageid": 1
}

### 本地 SAU 文件下载 
GET {{localhost}}download?filelink=/file/2015-11-07/db387029-c8fd-4985-820a-d1cb271a0d7d.doc

### 社团申请状态详情
GET {{localhost}}clubDetail?type=0&clubid=2511