@localhost=http://localhost:3000/
@sau=http://sau.scu.edu.cn/
@json=Content-Type: application/json

###
# 反馈
POST {{localhost}}feedback
{{json}}

{
    "data": "hello param"
}

###
# 搜索
POST {{localhost}}search
Content-Type: application/json;charset=UTF-8

{
    "ci": "",
    "cn": "Java",
    "pi": "1"
}

###
# 新闻列表
GET {{localhost}}newsList
{{json}}

{
    "page": "1"
}

###
# 新闻内容
GET {{localhost}}newsContent?newsid=6329

###
# 竟会是无效请求
POST {{sau}}/Club/LClub
Content-Type: application/x-www-form-urlencoded; charset=UTF-8

{
    "pi": "9"
}

###
# 申请状态
POST {{localhost}}searchStatue
{{json}}

{
    "clubname": "",
    "status": "",
    "pageid": 1
}